[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "asccore"
version = "0.1.0"
description = ""
authors = ["AscenderNative Core"]
readme = "README.md"
packages = [{include = "asc"}]
